// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: db_instances.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveDBInstances = `-- name: CountActiveDBInstances :one
SELECT count(*) FROM db_instances
WHERE deleted_at IS NULL
`

func (q *Queries) CountActiveDBInstances(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveDBInstances)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDBInstance = `-- name: CreateDBInstance :one
INSERT INTO db_instances (
    name, description, engine, engine_version, provider, region, instance_type,
    storage_gb, workspace, ssh_key_name, admin_username, admin_secret_name,
    postgres_port, postgres_image, created_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15
)
RETURNING id, name, description, engine, engine_version, provider, region, instance_type, storage_gb, status, container_status, status_message, workspace, ssh_key_name, provider_instance_id, availability_zone, public_ip, private_ip, security_group_id, volume_id, created_by, created_at, updated_at, deleted_at, admin_username, admin_secret_name, postgres_port, postgres_image
`

type CreateDBInstanceParams struct {
	Name            string      `json:"name"`
	Description     string      `json:"description"`
	Engine          string      `json:"engine"`
	EngineVersion   string      `json:"engine_version"`
	Provider        string      `json:"provider"`
	Region          string      `json:"region"`
	InstanceType    string      `json:"instance_type"`
	StorageGb       int32       `json:"storage_gb"`
	Workspace       string      `json:"workspace"`
	SshKeyName      string      `json:"ssh_key_name"`
	AdminUsername   string      `json:"admin_username"`
	AdminSecretName string      `json:"admin_secret_name"`
	PostgresPort    int32       `json:"postgres_port"`
	PostgresImage   string      `json:"postgres_image"`
	CreatedBy       pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreateDBInstance(ctx context.Context, arg CreateDBInstanceParams) (DbInstance, error) {
	row := q.db.QueryRow(ctx, createDBInstance,
		arg.Name,
		arg.Description,
		arg.Engine,
		arg.EngineVersion,
		arg.Provider,
		arg.Region,
		arg.InstanceType,
		arg.StorageGb,
		arg.Workspace,
		arg.SshKeyName,
		arg.AdminUsername,
		arg.AdminSecretName,
		arg.PostgresPort,
		arg.PostgresImage,
		arg.CreatedBy,
	)
	var i DbInstance
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Engine,
		&i.EngineVersion,
		&i.Provider,
		&i.Region,
		&i.InstanceType,
		&i.StorageGb,
		&i.Status,
		&i.ContainerStatus,
		&i.StatusMessage,
		&i.Workspace,
		&i.SshKeyName,
		&i.ProviderInstanceID,
		&i.AvailabilityZone,
		&i.PublicIp,
		&i.PrivateIp,
		&i.SecurityGroupID,
		&i.VolumeID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.AdminUsername,
		&i.AdminSecretName,
		&i.PostgresPort,
		&i.PostgresImage,
	)
	return i, err
}

const getDBInstanceByID = `-- name: GetDBInstanceByID :one
SELECT id, name, description, engine, engine_version, provider, region, instance_type, storage_gb, status, container_status, status_message, workspace, ssh_key_name, provider_instance_id, availability_zone, public_ip, private_ip, security_group_id, volume_id, created_by, created_at, updated_at, deleted_at, admin_username, admin_secret_name, postgres_port, postgres_image FROM db_instances
WHERE id = $1 AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetDBInstanceByID(ctx context.Context, id pgtype.UUID) (DbInstance, error) {
	row := q.db.QueryRow(ctx, getDBInstanceByID, id)
	var i DbInstance
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Engine,
		&i.EngineVersion,
		&i.Provider,
		&i.Region,
		&i.InstanceType,
		&i.StorageGb,
		&i.Status,
		&i.ContainerStatus,
		&i.StatusMessage,
		&i.Workspace,
		&i.SshKeyName,
		&i.ProviderInstanceID,
		&i.AvailabilityZone,
		&i.PublicIp,
		&i.PrivateIp,
		&i.SecurityGroupID,
		&i.VolumeID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.AdminUsername,
		&i.AdminSecretName,
		&i.PostgresPort,
		&i.PostgresImage,
	)
	return i, err
}

const getDBInstanceByName = `-- name: GetDBInstanceByName :one
SELECT id, name, description, engine, engine_version, provider, region, instance_type, storage_gb, status, container_status, status_message, workspace, ssh_key_name, provider_instance_id, availability_zone, public_ip, private_ip, security_group_id, volume_id, created_by, created_at, updated_at, deleted_at, admin_username, admin_secret_name, postgres_port, postgres_image FROM db_instances
WHERE name = $1 AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetDBInstanceByName(ctx context.Context, name string) (DbInstance, error) {
	row := q.db.QueryRow(ctx, getDBInstanceByName, name)
	var i DbInstance
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Engine,
		&i.EngineVersion,
		&i.Provider,
		&i.Region,
		&i.InstanceType,
		&i.StorageGb,
		&i.Status,
		&i.ContainerStatus,
		&i.StatusMessage,
		&i.Workspace,
		&i.SshKeyName,
		&i.ProviderInstanceID,
		&i.AvailabilityZone,
		&i.PublicIp,
		&i.PrivateIp,
		&i.SecurityGroupID,
		&i.VolumeID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.AdminUsername,
		&i.AdminSecretName,
		&i.PostgresPort,
		&i.PostgresImage,
	)
	return i, err
}

const listDBInstances = `-- name: ListDBInstances :many
SELECT id, name, description, engine, engine_version, provider, region, instance_type, storage_gb, status, container_status, status_message, workspace, ssh_key_name, provider_instance_id, availability_zone, public_ip, private_ip, security_group_id, volume_id, created_by, created_at, updated_at, deleted_at, admin_username, admin_secret_name, postgres_port, postgres_image FROM db_instances
WHERE deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListDBInstances(ctx context.Context) ([]DbInstance, error) {
	rows, err := q.db.Query(ctx, listDBInstances)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DbInstance
	for rows.Next() {
		var i DbInstance
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Engine,
			&i.EngineVersion,
			&i.Provider,
			&i.Region,
			&i.InstanceType,
			&i.StorageGb,
			&i.Status,
			&i.ContainerStatus,
			&i.StatusMessage,
			&i.Workspace,
			&i.SshKeyName,
			&i.ProviderInstanceID,
			&i.AvailabilityZone,
			&i.PublicIp,
			&i.PrivateIp,
			&i.SecurityGroupID,
			&i.VolumeID,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.AdminUsername,
			&i.AdminSecretName,
			&i.PostgresPort,
			&i.PostgresImage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markDBInstanceContainerStatus = `-- name: MarkDBInstanceContainerStatus :execrows
UPDATE db_instances
SET container_status = $2,
    status_message = $3,
    updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
`

type MarkDBInstanceContainerStatusParams struct {
	ID              pgtype.UUID `json:"id"`
	ContainerStatus string      `json:"container_status"`
	StatusMessage   pgtype.Text `json:"status_message"`
}

func (q *Queries) MarkDBInstanceContainerStatus(ctx context.Context, arg MarkDBInstanceContainerStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, markDBInstanceContainerStatus, arg.ID, arg.ContainerStatus, arg.StatusMessage)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markDBInstanceProvisioned = `-- name: MarkDBInstanceProvisioned :one
UPDATE db_instances
SET status = 'running',
    status_message = NULL,
    provider_instance_id = $2,
    availability_zone = $3,
    public_ip = $4,
    private_ip = $5,
    security_group_id = $6,
    volume_id = $7,
    updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, name, description, engine, engine_version, provider, region, instance_type, storage_gb, status, container_status, status_message, workspace, ssh_key_name, provider_instance_id, availability_zone, public_ip, private_ip, security_group_id, volume_id, created_by, created_at, updated_at, deleted_at, admin_username, admin_secret_name, postgres_port, postgres_image
`

type MarkDBInstanceProvisionedParams struct {
	ID                 pgtype.UUID `json:"id"`
	ProviderInstanceID pgtype.Text `json:"provider_instance_id"`
	AvailabilityZone   pgtype.Text `json:"availability_zone"`
	PublicIp           pgtype.Text `json:"public_ip"`
	PrivateIp          pgtype.Text `json:"private_ip"`
	SecurityGroupID    pgtype.Text `json:"security_group_id"`
	VolumeID           pgtype.Text `json:"volume_id"`
}

func (q *Queries) MarkDBInstanceProvisioned(ctx context.Context, arg MarkDBInstanceProvisionedParams) (DbInstance, error) {
	row := q.db.QueryRow(ctx, markDBInstanceProvisioned,
		arg.ID,
		arg.ProviderInstanceID,
		arg.AvailabilityZone,
		arg.PublicIp,
		arg.PrivateIp,
		arg.SecurityGroupID,
		arg.VolumeID,
	)
	var i DbInstance
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Engine,
		&i.EngineVersion,
		&i.Provider,
		&i.Region,
		&i.InstanceType,
		&i.StorageGb,
		&i.Status,
		&i.ContainerStatus,
		&i.StatusMessage,
		&i.Workspace,
		&i.SshKeyName,
		&i.ProviderInstanceID,
		&i.AvailabilityZone,
		&i.PublicIp,
		&i.PrivateIp,
		&i.SecurityGroupID,
		&i.VolumeID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.AdminUsername,
		&i.AdminSecretName,
		&i.PostgresPort,
		&i.PostgresImage,
	)
	return i, err
}

const markDBInstanceStatus = `-- name: MarkDBInstanceStatus :execrows
UPDATE db_instances
SET status = $2,
    status_message = $3,
    updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
`

type MarkDBInstanceStatusParams struct {
	ID            pgtype.UUID `json:"id"`
	Status        string      `json:"status"`
	StatusMessage pgtype.Text `json:"status_message"`
}

func (q *Queries) MarkDBInstanceStatus(ctx context.Context, arg MarkDBInstanceStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, markDBInstanceStatus, arg.ID, arg.Status, arg.StatusMessage)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const softDeleteDBInstance = `-- name: SoftDeleteDBInstance :execrows
UPDATE db_instances
SET deleted_at = now(), status = 'deleted', updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteDBInstance(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteDBInstance, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
