// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: deployments.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDeployment = `-- name: CreateDeployment :one
INSERT INTO deployments (
    service_id, environment, image_tag, previous_image_tag, git_commit_sha, git_branch,
    triggered_by_user_id, trigger_type, ci_run_url, deploy_strategy, gitops_commit_sha,
    status, started_at, is_rollback, rolled_back_from_deployment_id
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10, $11,
    $12, $13, $14, $15
)
RETURNING id, service_id, environment, image_tag, previous_image_tag, git_commit_sha, git_branch, triggered_by_user_id, trigger_type, ci_run_url, deploy_strategy, gitops_commit_sha, status, started_at, completed_at, failure_reason, is_rollback, rolled_back_from_deployment_id, created_at
`

type CreateDeploymentParams struct {
	ServiceID                  pgtype.UUID        `json:"service_id"`
	Environment                string             `json:"environment"`
	ImageTag                   string             `json:"image_tag"`
	PreviousImageTag           pgtype.Text        `json:"previous_image_tag"`
	GitCommitSha               pgtype.Text        `json:"git_commit_sha"`
	GitBranch                  pgtype.Text        `json:"git_branch"`
	TriggeredByUserID          pgtype.UUID        `json:"triggered_by_user_id"`
	TriggerType                string             `json:"trigger_type"`
	CiRunUrl                   pgtype.Text        `json:"ci_run_url"`
	DeployStrategy             string             `json:"deploy_strategy"`
	GitopsCommitSha            pgtype.Text        `json:"gitops_commit_sha"`
	Status                     string             `json:"status"`
	StartedAt                  pgtype.Timestamptz `json:"started_at"`
	IsRollback                 bool               `json:"is_rollback"`
	RolledBackFromDeploymentID pgtype.UUID        `json:"rolled_back_from_deployment_id"`
}

func (q *Queries) CreateDeployment(ctx context.Context, arg CreateDeploymentParams) (Deployment, error) {
	row := q.db.QueryRow(ctx, createDeployment,
		arg.ServiceID,
		arg.Environment,
		arg.ImageTag,
		arg.PreviousImageTag,
		arg.GitCommitSha,
		arg.GitBranch,
		arg.TriggeredByUserID,
		arg.TriggerType,
		arg.CiRunUrl,
		arg.DeployStrategy,
		arg.GitopsCommitSha,
		arg.Status,
		arg.StartedAt,
		arg.IsRollback,
		arg.RolledBackFromDeploymentID,
	)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.ServiceID,
		&i.Environment,
		&i.ImageTag,
		&i.PreviousImageTag,
		&i.GitCommitSha,
		&i.GitBranch,
		&i.TriggeredByUserID,
		&i.TriggerType,
		&i.CiRunUrl,
		&i.DeployStrategy,
		&i.GitopsCommitSha,
		&i.Status,
		&i.StartedAt,
		&i.CompletedAt,
		&i.FailureReason,
		&i.IsRollback,
		&i.RolledBackFromDeploymentID,
		&i.CreatedAt,
	)
	return i, err
}

const getCurrentDeployment = `-- name: GetCurrentDeployment :one
SELECT id, service_id, environment, image_tag, previous_image_tag, git_commit_sha, git_branch, triggered_by_user_id, trigger_type, ci_run_url, deploy_strategy, gitops_commit_sha, status, started_at, completed_at, failure_reason, is_rollback, rolled_back_from_deployment_id, created_at FROM deployments
WHERE service_id = $1 AND environment = $2 AND status = 'succeeded'
ORDER BY completed_at DESC
LIMIT 1
`

type GetCurrentDeploymentParams struct {
	ServiceID   pgtype.UUID `json:"service_id"`
	Environment string      `json:"environment"`
}

// Latest successful deployment for a service+environment, i.e. what's actually running.
func (q *Queries) GetCurrentDeployment(ctx context.Context, arg GetCurrentDeploymentParams) (Deployment, error) {
	row := q.db.QueryRow(ctx, getCurrentDeployment, arg.ServiceID, arg.Environment)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.ServiceID,
		&i.Environment,
		&i.ImageTag,
		&i.PreviousImageTag,
		&i.GitCommitSha,
		&i.GitBranch,
		&i.TriggeredByUserID,
		&i.TriggerType,
		&i.CiRunUrl,
		&i.DeployStrategy,
		&i.GitopsCommitSha,
		&i.Status,
		&i.StartedAt,
		&i.CompletedAt,
		&i.FailureReason,
		&i.IsRollback,
		&i.RolledBackFromDeploymentID,
		&i.CreatedAt,
	)
	return i, err
}

const getDeploymentByID = `-- name: GetDeploymentByID :one
SELECT id, service_id, environment, image_tag, previous_image_tag, git_commit_sha, git_branch, triggered_by_user_id, trigger_type, ci_run_url, deploy_strategy, gitops_commit_sha, status, started_at, completed_at, failure_reason, is_rollback, rolled_back_from_deployment_id, created_at FROM deployments
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetDeploymentByID(ctx context.Context, id pgtype.UUID) (Deployment, error) {
	row := q.db.QueryRow(ctx, getDeploymentByID, id)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.ServiceID,
		&i.Environment,
		&i.ImageTag,
		&i.PreviousImageTag,
		&i.GitCommitSha,
		&i.GitBranch,
		&i.TriggeredByUserID,
		&i.TriggerType,
		&i.CiRunUrl,
		&i.DeployStrategy,
		&i.GitopsCommitSha,
		&i.Status,
		&i.StartedAt,
		&i.CompletedAt,
		&i.FailureReason,
		&i.IsRollback,
		&i.RolledBackFromDeploymentID,
		&i.CreatedAt,
	)
	return i, err
}

const listDeploymentsByService = `-- name: ListDeploymentsByService :many
SELECT id, service_id, environment, image_tag, previous_image_tag, git_commit_sha, git_branch, triggered_by_user_id, trigger_type, ci_run_url, deploy_strategy, gitops_commit_sha, status, started_at, completed_at, failure_reason, is_rollback, rolled_back_from_deployment_id, created_at FROM deployments
WHERE service_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListDeploymentsByService(ctx context.Context, serviceID pgtype.UUID) ([]Deployment, error) {
	rows, err := q.db.Query(ctx, listDeploymentsByService, serviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Deployment
	for rows.Next() {
		var i Deployment
		if err := rows.Scan(
			&i.ID,
			&i.ServiceID,
			&i.Environment,
			&i.ImageTag,
			&i.PreviousImageTag,
			&i.GitCommitSha,
			&i.GitBranch,
			&i.TriggeredByUserID,
			&i.TriggerType,
			&i.CiRunUrl,
			&i.DeployStrategy,
			&i.GitopsCommitSha,
			&i.Status,
			&i.StartedAt,
			&i.CompletedAt,
			&i.FailureReason,
			&i.IsRollback,
			&i.RolledBackFromDeploymentID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeploymentsByServiceEnvironment = `-- name: ListDeploymentsByServiceEnvironment :many
SELECT id, service_id, environment, image_tag, previous_image_tag, git_commit_sha, git_branch, triggered_by_user_id, trigger_type, ci_run_url, deploy_strategy, gitops_commit_sha, status, started_at, completed_at, failure_reason, is_rollback, rolled_back_from_deployment_id, created_at FROM deployments
WHERE service_id = $1 AND environment = $2
ORDER BY created_at DESC
`

type ListDeploymentsByServiceEnvironmentParams struct {
	ServiceID   pgtype.UUID `json:"service_id"`
	Environment string      `json:"environment"`
}

func (q *Queries) ListDeploymentsByServiceEnvironment(ctx context.Context, arg ListDeploymentsByServiceEnvironmentParams) ([]Deployment, error) {
	rows, err := q.db.Query(ctx, listDeploymentsByServiceEnvironment, arg.ServiceID, arg.Environment)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Deployment
	for rows.Next() {
		var i Deployment
		if err := rows.Scan(
			&i.ID,
			&i.ServiceID,
			&i.Environment,
			&i.ImageTag,
			&i.PreviousImageTag,
			&i.GitCommitSha,
			&i.GitBranch,
			&i.TriggeredByUserID,
			&i.TriggerType,
			&i.CiRunUrl,
			&i.DeployStrategy,
			&i.GitopsCommitSha,
			&i.Status,
			&i.StartedAt,
			&i.CompletedAt,
			&i.FailureReason,
			&i.IsRollback,
			&i.RolledBackFromDeploymentID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDeploymentStatus = `-- name: UpdateDeploymentStatus :one
UPDATE deployments
SET status = $2, completed_at = $3, failure_reason = $4
WHERE id = $1
RETURNING id, service_id, environment, image_tag, previous_image_tag, git_commit_sha, git_branch, triggered_by_user_id, trigger_type, ci_run_url, deploy_strategy, gitops_commit_sha, status, started_at, completed_at, failure_reason, is_rollback, rolled_back_from_deployment_id, created_at
`

type UpdateDeploymentStatusParams struct {
	ID            pgtype.UUID        `json:"id"`
	Status        string             `json:"status"`
	CompletedAt   pgtype.Timestamptz `json:"completed_at"`
	FailureReason pgtype.Text        `json:"failure_reason"`
}

// The only mutation ever allowed on a deployment row after creation.
func (q *Queries) UpdateDeploymentStatus(ctx context.Context, arg UpdateDeploymentStatusParams) (Deployment, error) {
	row := q.db.QueryRow(ctx, updateDeploymentStatus,
		arg.ID,
		arg.Status,
		arg.CompletedAt,
		arg.FailureReason,
	)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.ServiceID,
		&i.Environment,
		&i.ImageTag,
		&i.PreviousImageTag,
		&i.GitCommitSha,
		&i.GitBranch,
		&i.TriggeredByUserID,
		&i.TriggerType,
		&i.CiRunUrl,
		&i.DeployStrategy,
		&i.GitopsCommitSha,
		&i.Status,
		&i.StartedAt,
		&i.CompletedAt,
		&i.FailureReason,
		&i.IsRollback,
		&i.RolledBackFromDeploymentID,
		&i.CreatedAt,
	)
	return i, err
}
