// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: deployments.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveDeploymentsByInstanceID = `-- name: CountActiveDeploymentsByInstanceID :one
SELECT count(*) FROM deployment
WHERE deployment_instance_id = $1
  AND status NOT IN ('stopped', 'failed')
`

func (q *Queries) CountActiveDeploymentsByInstanceID(ctx context.Context, deploymentInstanceID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveDeploymentsByInstanceID, deploymentInstanceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDeployment = `-- name: CreateDeployment :one
INSERT INTO deployment (
    deployment_instance_id, repo_id, registry_id, image_name, image_tag, name,
    namespace, replicas, resources, env_vars, secret_refs, expose, status,
    current_revision, k8s_deployment_name, created_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, 'pending', 1, $13, $14
)
RETURNING id, deployment_instance_id, repo_id, registry_id, image_name, image_tag, name, namespace, replicas, resources, env_vars, secret_refs, expose, status, current_revision, k8s_deployment_name, last_error, created_by, created_at, updated_at
`

type CreateDeploymentParams struct {
	DeploymentInstanceID pgtype.UUID `json:"deployment_instance_id"`
	RepoID               pgtype.UUID `json:"repo_id"`
	RegistryID           pgtype.UUID `json:"registry_id"`
	ImageName            string      `json:"image_name"`
	ImageTag             string      `json:"image_tag"`
	Name                 string      `json:"name"`
	Namespace            string      `json:"namespace"`
	Replicas             int32       `json:"replicas"`
	Resources            []byte      `json:"resources"`
	EnvVars              []byte      `json:"env_vars"`
	SecretRefs           []byte      `json:"secret_refs"`
	Expose               []byte      `json:"expose"`
	K8sDeploymentName    pgtype.Text `json:"k8s_deployment_name"`
	CreatedBy            pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreateDeployment(ctx context.Context, arg CreateDeploymentParams) (Deployment, error) {
	row := q.db.QueryRow(ctx, createDeployment,
		arg.DeploymentInstanceID,
		arg.RepoID,
		arg.RegistryID,
		arg.ImageName,
		arg.ImageTag,
		arg.Name,
		arg.Namespace,
		arg.Replicas,
		arg.Resources,
		arg.EnvVars,
		arg.SecretRefs,
		arg.Expose,
		arg.K8sDeploymentName,
		arg.CreatedBy,
	)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.DeploymentInstanceID,
		&i.RepoID,
		&i.RegistryID,
		&i.ImageName,
		&i.ImageTag,
		&i.Name,
		&i.Namespace,
		&i.Replicas,
		&i.Resources,
		&i.EnvVars,
		&i.SecretRefs,
		&i.Expose,
		&i.Status,
		&i.CurrentRevision,
		&i.K8sDeploymentName,
		&i.LastError,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createDeploymentRevision = `-- name: CreateDeploymentRevision :one
INSERT INTO deploymentrevision (
    deployment_id, revision_no, image_tag, config_snapshot, status, triggered_by
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, deployment_id, revision_no, image_tag, config_snapshot, status, triggered_by, created_at
`

type CreateDeploymentRevisionParams struct {
	DeploymentID   pgtype.UUID `json:"deployment_id"`
	RevisionNo     int32       `json:"revision_no"`
	ImageTag       string      `json:"image_tag"`
	ConfigSnapshot []byte      `json:"config_snapshot"`
	Status         string      `json:"status"`
	TriggeredBy    pgtype.UUID `json:"triggered_by"`
}

func (q *Queries) CreateDeploymentRevision(ctx context.Context, arg CreateDeploymentRevisionParams) (Deploymentrevision, error) {
	row := q.db.QueryRow(ctx, createDeploymentRevision,
		arg.DeploymentID,
		arg.RevisionNo,
		arg.ImageTag,
		arg.ConfigSnapshot,
		arg.Status,
		arg.TriggeredBy,
	)
	var i Deploymentrevision
	err := row.Scan(
		&i.ID,
		&i.DeploymentID,
		&i.RevisionNo,
		&i.ImageTag,
		&i.ConfigSnapshot,
		&i.Status,
		&i.TriggeredBy,
		&i.CreatedAt,
	)
	return i, err
}

const deleteDeployment = `-- name: DeleteDeployment :execrows
DELETE FROM deployment
WHERE id = $1
`

func (q *Queries) DeleteDeployment(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteDeployment, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getDeploymentByID = `-- name: GetDeploymentByID :one
SELECT id, deployment_instance_id, repo_id, registry_id, image_name, image_tag, name, namespace, replicas, resources, env_vars, secret_refs, expose, status, current_revision, k8s_deployment_name, last_error, created_by, created_at, updated_at FROM deployment
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetDeploymentByID(ctx context.Context, id pgtype.UUID) (Deployment, error) {
	row := q.db.QueryRow(ctx, getDeploymentByID, id)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.DeploymentInstanceID,
		&i.RepoID,
		&i.RegistryID,
		&i.ImageName,
		&i.ImageTag,
		&i.Name,
		&i.Namespace,
		&i.Replicas,
		&i.Resources,
		&i.EnvVars,
		&i.SecretRefs,
		&i.Expose,
		&i.Status,
		&i.CurrentRevision,
		&i.K8sDeploymentName,
		&i.LastError,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLatestDeploymentRevision = `-- name: GetLatestDeploymentRevision :one
SELECT id, deployment_id, revision_no, image_tag, config_snapshot, status, triggered_by, created_at FROM deploymentrevision
WHERE deployment_id = $1
ORDER BY revision_no DESC
LIMIT 1
`

func (q *Queries) GetLatestDeploymentRevision(ctx context.Context, deploymentID pgtype.UUID) (Deploymentrevision, error) {
	row := q.db.QueryRow(ctx, getLatestDeploymentRevision, deploymentID)
	var i Deploymentrevision
	err := row.Scan(
		&i.ID,
		&i.DeploymentID,
		&i.RevisionNo,
		&i.ImageTag,
		&i.ConfigSnapshot,
		&i.Status,
		&i.TriggeredBy,
		&i.CreatedAt,
	)
	return i, err
}

const listDeployments = `-- name: ListDeployments :many
SELECT id, deployment_instance_id, repo_id, registry_id, image_name, image_tag, name, namespace, replicas, resources, env_vars, secret_refs, expose, status, current_revision, k8s_deployment_name, last_error, created_by, created_at, updated_at FROM deployment
ORDER BY created_at DESC
`

func (q *Queries) ListDeployments(ctx context.Context) ([]Deployment, error) {
	rows, err := q.db.Query(ctx, listDeployments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Deployment
	for rows.Next() {
		var i Deployment
		if err := rows.Scan(
			&i.ID,
			&i.DeploymentInstanceID,
			&i.RepoID,
			&i.RegistryID,
			&i.ImageName,
			&i.ImageTag,
			&i.Name,
			&i.Namespace,
			&i.Replicas,
			&i.Resources,
			&i.EnvVars,
			&i.SecretRefs,
			&i.Expose,
			&i.Status,
			&i.CurrentRevision,
			&i.K8sDeploymentName,
			&i.LastError,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markDeploymentDeploying = `-- name: MarkDeploymentDeploying :one
UPDATE deployment
SET status = 'deploying',
    last_error = NULL,
    updated_at = now()
WHERE id = $1
RETURNING id, deployment_instance_id, repo_id, registry_id, image_name, image_tag, name, namespace, replicas, resources, env_vars, secret_refs, expose, status, current_revision, k8s_deployment_name, last_error, created_by, created_at, updated_at
`

func (q *Queries) MarkDeploymentDeploying(ctx context.Context, id pgtype.UUID) (Deployment, error) {
	row := q.db.QueryRow(ctx, markDeploymentDeploying, id)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.DeploymentInstanceID,
		&i.RepoID,
		&i.RegistryID,
		&i.ImageName,
		&i.ImageTag,
		&i.Name,
		&i.Namespace,
		&i.Replicas,
		&i.Resources,
		&i.EnvVars,
		&i.SecretRefs,
		&i.Expose,
		&i.Status,
		&i.CurrentRevision,
		&i.K8sDeploymentName,
		&i.LastError,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markDeploymentStatus = `-- name: MarkDeploymentStatus :execrows
UPDATE deployment
SET status = $2,
    last_error = $3,
    updated_at = now()
WHERE id = $1
`

type MarkDeploymentStatusParams struct {
	ID        pgtype.UUID `json:"id"`
	Status    string      `json:"status"`
	LastError pgtype.Text `json:"last_error"`
}

func (q *Queries) MarkDeploymentStatus(ctx context.Context, arg MarkDeploymentStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, markDeploymentStatus, arg.ID, arg.Status, arg.LastError)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
