// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: deploymentinstance.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDeploymentInstance = `-- name: CreateDeploymentInstance :one
INSERT INTO deploymentinstance (
    name, workspace, ssh_key_name, max_deployments, created_by
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, name, ec2_instance_id, public_ip, private_ip, api_server_url, auth_type, credentials_ref, max_deployments, status, last_error, workspace, ssh_key_name, security_group_id, created_by, created_at, updated_at
`

type CreateDeploymentInstanceParams struct {
	Name           string      `json:"name"`
	Workspace      string      `json:"workspace"`
	SshKeyName     string      `json:"ssh_key_name"`
	MaxDeployments int32       `json:"max_deployments"`
	CreatedBy      pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreateDeploymentInstance(ctx context.Context, arg CreateDeploymentInstanceParams) (Deploymentinstance, error) {
	row := q.db.QueryRow(ctx, createDeploymentInstance,
		arg.Name,
		arg.Workspace,
		arg.SshKeyName,
		arg.MaxDeployments,
		arg.CreatedBy,
	)
	var i Deploymentinstance
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Ec2InstanceID,
		&i.PublicIp,
		&i.PrivateIp,
		&i.ApiServerUrl,
		&i.AuthType,
		&i.CredentialsRef,
		&i.MaxDeployments,
		&i.Status,
		&i.LastError,
		&i.Workspace,
		&i.SshKeyName,
		&i.SecurityGroupID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLiveDeploymentInstance = `-- name: GetLiveDeploymentInstance :one
SELECT id, name, ec2_instance_id, public_ip, private_ip, api_server_url, auth_type, credentials_ref, max_deployments, status, last_error, workspace, ssh_key_name, security_group_id, created_by, created_at, updated_at FROM deploymentinstance
WHERE status <> 'terminated'
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetLiveDeploymentInstance(ctx context.Context) (Deploymentinstance, error) {
	row := q.db.QueryRow(ctx, getLiveDeploymentInstance)
	var i Deploymentinstance
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Ec2InstanceID,
		&i.PublicIp,
		&i.PrivateIp,
		&i.ApiServerUrl,
		&i.AuthType,
		&i.CredentialsRef,
		&i.MaxDeployments,
		&i.Status,
		&i.LastError,
		&i.Workspace,
		&i.SshKeyName,
		&i.SecurityGroupID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markDeploymentInstanceProvisioned = `-- name: MarkDeploymentInstanceProvisioned :one
UPDATE deploymentinstance
SET status = 'active',
    last_error = NULL,
    ec2_instance_id = $2,
    public_ip = $3,
    private_ip = $4,
    api_server_url = $5,
    credentials_ref = $6,
    security_group_id = $7,
    updated_at = now()
WHERE id = $1 AND status <> 'terminated'
RETURNING id, name, ec2_instance_id, public_ip, private_ip, api_server_url, auth_type, credentials_ref, max_deployments, status, last_error, workspace, ssh_key_name, security_group_id, created_by, created_at, updated_at
`

type MarkDeploymentInstanceProvisionedParams struct {
	ID              pgtype.UUID `json:"id"`
	Ec2InstanceID   pgtype.Text `json:"ec2_instance_id"`
	PublicIp        pgtype.Text `json:"public_ip"`
	PrivateIp       pgtype.Text `json:"private_ip"`
	ApiServerUrl    pgtype.Text `json:"api_server_url"`
	CredentialsRef  pgtype.Text `json:"credentials_ref"`
	SecurityGroupID pgtype.Text `json:"security_group_id"`
}

func (q *Queries) MarkDeploymentInstanceProvisioned(ctx context.Context, arg MarkDeploymentInstanceProvisionedParams) (Deploymentinstance, error) {
	row := q.db.QueryRow(ctx, markDeploymentInstanceProvisioned,
		arg.ID,
		arg.Ec2InstanceID,
		arg.PublicIp,
		arg.PrivateIp,
		arg.ApiServerUrl,
		arg.CredentialsRef,
		arg.SecurityGroupID,
	)
	var i Deploymentinstance
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Ec2InstanceID,
		&i.PublicIp,
		&i.PrivateIp,
		&i.ApiServerUrl,
		&i.AuthType,
		&i.CredentialsRef,
		&i.MaxDeployments,
		&i.Status,
		&i.LastError,
		&i.Workspace,
		&i.SshKeyName,
		&i.SecurityGroupID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markDeploymentInstanceStatus = `-- name: MarkDeploymentInstanceStatus :execrows
UPDATE deploymentinstance
SET status = $2,
    last_error = $3,
    updated_at = now()
WHERE id = $1 AND status <> 'terminated'
`

type MarkDeploymentInstanceStatusParams struct {
	ID        pgtype.UUID `json:"id"`
	Status    string      `json:"status"`
	LastError pgtype.Text `json:"last_error"`
}

func (q *Queries) MarkDeploymentInstanceStatus(ctx context.Context, arg MarkDeploymentInstanceStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, markDeploymentInstanceStatus, arg.ID, arg.Status, arg.LastError)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markDeploymentInstanceTerminated = `-- name: MarkDeploymentInstanceTerminated :execrows
UPDATE deploymentinstance
SET status = 'terminated',
    credentials_ref = NULL,
    updated_at = now()
WHERE id = $1 AND status <> 'terminated'
`

func (q *Queries) MarkDeploymentInstanceTerminated(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, markDeploymentInstanceTerminated, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
