// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: lookups.sql

package store

import (
	"context"
)

const listLanguages = `-- name: ListLanguages :many
SELECT id, code, label FROM languages
ORDER BY id
`

func (q *Queries) ListLanguages(ctx context.Context) ([]Language, error) {
	rows, err := q.db.Query(ctx, listLanguages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Language
	for rows.Next() {
		var i Language
		if err := rows.Scan(&i.ID, &i.Code, &i.Label); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRegistryProviders = `-- name: ListRegistryProviders :many
SELECT id, code, label FROM registry_providers
ORDER BY id
`

func (q *Queries) ListRegistryProviders(ctx context.Context) ([]RegistryProvider, error) {
	rows, err := q.db.Query(ctx, listRegistryProviders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RegistryProvider
	for rows.Next() {
		var i RegistryProvider
		if err := rows.Scan(&i.ID, &i.Code, &i.Label); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRepoProviders = `-- name: ListRepoProviders :many
SELECT id, code FROM repo_providers
ORDER BY id
`

func (q *Queries) ListRepoProviders(ctx context.Context) ([]RepoProvider, error) {
	rows, err := q.db.Query(ctx, listRepoProviders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RepoProvider
	for rows.Next() {
		var i RepoProvider
		if err := rows.Scan(&i.ID, &i.Code); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRepoTemplates = `-- name: ListRepoTemplates :many
SELECT id, name, slug, template_owner, template_repo, is_active, created_at FROM repo_templates
WHERE is_active = true
ORDER BY id
`

func (q *Queries) ListRepoTemplates(ctx context.Context) ([]RepoTemplate, error) {
	rows, err := q.db.Query(ctx, listRepoTemplates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RepoTemplate
	for rows.Next() {
		var i RepoTemplate
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.TemplateOwner,
			&i.TemplateRepo,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
