// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: managed_databases.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createManagedDatabase = `-- name: CreateManagedDatabase :one
INSERT INTO managed_databases (
    db_instance_id, name, username, password, allocated_mb,
    status, connection_string, created_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, db_instance_id, name, username, password, allocated_mb, status, connection_string, created_by, created_at, updated_at, deleted_at
`

type CreateManagedDatabaseParams struct {
	DbInstanceID     pgtype.UUID `json:"db_instance_id"`
	Name             string      `json:"name"`
	Username         string      `json:"username"`
	Password         string      `json:"password"`
	AllocatedMb      int32       `json:"allocated_mb"`
	Status           string      `json:"status"`
	ConnectionString string      `json:"connection_string"`
	CreatedBy        pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreateManagedDatabase(ctx context.Context, arg CreateManagedDatabaseParams) (ManagedDatabase, error) {
	row := q.db.QueryRow(ctx, createManagedDatabase,
		arg.DbInstanceID,
		arg.Name,
		arg.Username,
		arg.Password,
		arg.AllocatedMb,
		arg.Status,
		arg.ConnectionString,
		arg.CreatedBy,
	)
	var i ManagedDatabase
	err := row.Scan(
		&i.ID,
		&i.DbInstanceID,
		&i.Name,
		&i.Username,
		&i.Password,
		&i.AllocatedMb,
		&i.Status,
		&i.ConnectionString,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getManagedDatabaseByID = `-- name: GetManagedDatabaseByID :one
SELECT id, db_instance_id, name, username, password, allocated_mb, status, connection_string, created_by, created_at, updated_at, deleted_at FROM managed_databases
WHERE id = $1 AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetManagedDatabaseByID(ctx context.Context, id pgtype.UUID) (ManagedDatabase, error) {
	row := q.db.QueryRow(ctx, getManagedDatabaseByID, id)
	var i ManagedDatabase
	err := row.Scan(
		&i.ID,
		&i.DbInstanceID,
		&i.Name,
		&i.Username,
		&i.Password,
		&i.AllocatedMb,
		&i.Status,
		&i.ConnectionString,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getManagedDatabaseByName = `-- name: GetManagedDatabaseByName :one
SELECT id, db_instance_id, name, username, password, allocated_mb, status, connection_string, created_by, created_at, updated_at, deleted_at FROM managed_databases
WHERE db_instance_id = $1 AND name = $2 AND deleted_at IS NULL
LIMIT 1
`

type GetManagedDatabaseByNameParams struct {
	DbInstanceID pgtype.UUID `json:"db_instance_id"`
	Name         string      `json:"name"`
}

func (q *Queries) GetManagedDatabaseByName(ctx context.Context, arg GetManagedDatabaseByNameParams) (ManagedDatabase, error) {
	row := q.db.QueryRow(ctx, getManagedDatabaseByName, arg.DbInstanceID, arg.Name)
	var i ManagedDatabase
	err := row.Scan(
		&i.ID,
		&i.DbInstanceID,
		&i.Name,
		&i.Username,
		&i.Password,
		&i.AllocatedMb,
		&i.Status,
		&i.ConnectionString,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getTotalAllocatedMB = `-- name: GetTotalAllocatedMB :one
SELECT COALESCE(SUM(allocated_mb), 0)::BIGINT AS total_allocated_mb
FROM managed_databases
WHERE status = 'active' AND deleted_at IS NULL
`

func (q *Queries) GetTotalAllocatedMB(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getTotalAllocatedMB)
	var total_allocated_mb int64
	err := row.Scan(&total_allocated_mb)
	return total_allocated_mb, err
}

const getTotalAllocatedMBByInstanceID = `-- name: GetTotalAllocatedMBByInstanceID :one
SELECT COALESCE(SUM(allocated_mb), 0)::BIGINT AS total_allocated_mb
FROM managed_databases
WHERE db_instance_id = $1 AND status = 'active' AND deleted_at IS NULL
`

func (q *Queries) GetTotalAllocatedMBByInstanceID(ctx context.Context, dbInstanceID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getTotalAllocatedMBByInstanceID, dbInstanceID)
	var total_allocated_mb int64
	err := row.Scan(&total_allocated_mb)
	return total_allocated_mb, err
}

const listActiveManagedDatabasesByInstanceID = `-- name: ListActiveManagedDatabasesByInstanceID :many
SELECT id, db_instance_id, name, username, password, allocated_mb, status, connection_string, created_by, created_at, updated_at, deleted_at FROM managed_databases
WHERE db_instance_id = $1 AND status = 'active' AND deleted_at IS NULL
ORDER BY created_at ASC
`

func (q *Queries) ListActiveManagedDatabasesByInstanceID(ctx context.Context, dbInstanceID pgtype.UUID) ([]ManagedDatabase, error) {
	rows, err := q.db.Query(ctx, listActiveManagedDatabasesByInstanceID, dbInstanceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ManagedDatabase
	for rows.Next() {
		var i ManagedDatabase
		if err := rows.Scan(
			&i.ID,
			&i.DbInstanceID,
			&i.Name,
			&i.Username,
			&i.Password,
			&i.AllocatedMb,
			&i.Status,
			&i.ConnectionString,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listManagedDatabases = `-- name: ListManagedDatabases :many
SELECT id, db_instance_id, name, username, password, allocated_mb, status, connection_string, created_by, created_at, updated_at, deleted_at FROM managed_databases
WHERE deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListManagedDatabases(ctx context.Context) ([]ManagedDatabase, error) {
	rows, err := q.db.Query(ctx, listManagedDatabases)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ManagedDatabase
	for rows.Next() {
		var i ManagedDatabase
		if err := rows.Scan(
			&i.ID,
			&i.DbInstanceID,
			&i.Name,
			&i.Username,
			&i.Password,
			&i.AllocatedMb,
			&i.Status,
			&i.ConnectionString,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listManagedDatabasesByInstanceID = `-- name: ListManagedDatabasesByInstanceID :many
SELECT id, db_instance_id, name, username, password, allocated_mb, status, connection_string, created_by, created_at, updated_at, deleted_at FROM managed_databases
WHERE db_instance_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListManagedDatabasesByInstanceID(ctx context.Context, dbInstanceID pgtype.UUID) ([]ManagedDatabase, error) {
	rows, err := q.db.Query(ctx, listManagedDatabasesByInstanceID, dbInstanceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ManagedDatabase
	for rows.Next() {
		var i ManagedDatabase
		if err := rows.Scan(
			&i.ID,
			&i.DbInstanceID,
			&i.Name,
			&i.Username,
			&i.Password,
			&i.AllocatedMb,
			&i.Status,
			&i.ConnectionString,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markManagedDatabaseStatus = `-- name: MarkManagedDatabaseStatus :execrows
UPDATE managed_databases
SET status = $2,
    updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
`

type MarkManagedDatabaseStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) MarkManagedDatabaseStatus(ctx context.Context, arg MarkManagedDatabaseStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, markManagedDatabaseStatus, arg.ID, arg.Status)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const softDeleteManagedDatabase = `-- name: SoftDeleteManagedDatabase :execrows
UPDATE managed_databases
SET deleted_at = now(),
    status = 'deleted',
    updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteManagedDatabase(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteManagedDatabase, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const softDeleteManagedDatabasesByInstanceID = `-- name: SoftDeleteManagedDatabasesByInstanceID :execrows
UPDATE managed_databases
SET deleted_at = now(),
    status = 'deleted',
    updated_at = now()
WHERE db_instance_id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteManagedDatabasesByInstanceID(ctx context.Context, dbInstanceID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteManagedDatabasesByInstanceID, dbInstanceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
