// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Language struct {
	ID    int16       `json:"id"`
	Code  string      `json:"code"`
	Label pgtype.Text `json:"label"`
}

type Repo struct {
	ID            pgtype.UUID        `json:"id"`
	Name          string             `json:"name"`
	FullName      pgtype.Text        `json:"full_name"`
	Owner         string             `json:"owner"`
	ProviderID    int16              `json:"provider_id"`
	ExternalID    pgtype.Text        `json:"external_id"`
	Url           pgtype.Text        `json:"url"`
	CloneUrlSsh   pgtype.Text        `json:"clone_url_ssh"`
	CloneUrlHttps pgtype.Text        `json:"clone_url_https"`
	DefaultBranch string             `json:"default_branch"`
	Visibility    string             `json:"visibility"`
	TemplateUsed  pgtype.Text        `json:"template_used"`
	Status        string             `json:"status"`
	ErrorMessage  pgtype.Text        `json:"error_message"`
	CreatedBy     pgtype.UUID        `json:"created_by"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type RepoProvider struct {
	ID   int16  `json:"id"`
	Code string `json:"code"`
}

type RepoTemplate struct {
	ID            int16              `json:"id"`
	Name          string             `json:"name"`
	Slug          string             `json:"slug"`
	TemplateOwner string             `json:"template_owner"`
	TemplateRepo  string             `json:"template_repo"`
	IsActive      bool               `json:"is_active"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type Role struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Team struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	Slug        string             `json:"slug"`
	Description pgtype.Text        `json:"description"`
	IsActive    bool               `json:"is_active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type TeamMember struct {
	ID         pgtype.UUID        `json:"id"`
	TeamID     pgtype.UUID        `json:"team_id"`
	UserID     pgtype.UUID        `json:"user_id"`
	RoleInTeam string             `json:"role_in_team"`
	IsPrimary  bool               `json:"is_primary"`
	JoinedAt   pgtype.Timestamptz `json:"joined_at"`
	LeftAt     pgtype.Timestamptz `json:"left_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	Username     string             `json:"username"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	FullName     pgtype.Text        `json:"full_name"`
	AvatarUrl    pgtype.Text        `json:"avatar_url"`
	ManagerID    pgtype.UUID        `json:"manager_id"`
	RoleID       pgtype.UUID        `json:"role_id"`
	IsActive     bool               `json:"is_active"`
	LastLoginAt  pgtype.Timestamptz `json:"last_login_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
