// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: project_environments.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addProjectEnvironment = `-- name: AddProjectEnvironment :one
INSERT INTO project_environments (project_id, environment, cluster_name, namespace, url, replicas)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, project_id, environment, cluster_name, namespace, url, replicas
`

type AddProjectEnvironmentParams struct {
	ProjectID   pgtype.UUID `json:"project_id"`
	Environment string      `json:"environment"`
	ClusterName pgtype.Text `json:"cluster_name"`
	Namespace   pgtype.Text `json:"namespace"`
	Url         pgtype.Text `json:"url"`
	Replicas    int32       `json:"replicas"`
}

func (q *Queries) AddProjectEnvironment(ctx context.Context, arg AddProjectEnvironmentParams) (ProjectEnvironment, error) {
	row := q.db.QueryRow(ctx, addProjectEnvironment,
		arg.ProjectID,
		arg.Environment,
		arg.ClusterName,
		arg.Namespace,
		arg.Url,
		arg.Replicas,
	)
	var i ProjectEnvironment
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Environment,
		&i.ClusterName,
		&i.Namespace,
		&i.Url,
		&i.Replicas,
	)
	return i, err
}

const getProjectEnvironment = `-- name: GetProjectEnvironment :one
SELECT id, project_id, environment, cluster_name, namespace, url, replicas FROM project_environments
WHERE project_id = $1 AND environment = $2
LIMIT 1
`

type GetProjectEnvironmentParams struct {
	ProjectID   pgtype.UUID `json:"project_id"`
	Environment string      `json:"environment"`
}

func (q *Queries) GetProjectEnvironment(ctx context.Context, arg GetProjectEnvironmentParams) (ProjectEnvironment, error) {
	row := q.db.QueryRow(ctx, getProjectEnvironment, arg.ProjectID, arg.Environment)
	var i ProjectEnvironment
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Environment,
		&i.ClusterName,
		&i.Namespace,
		&i.Url,
		&i.Replicas,
	)
	return i, err
}

const listProjectEnvironments = `-- name: ListProjectEnvironments :many
SELECT id, project_id, environment, cluster_name, namespace, url, replicas FROM project_environments
WHERE project_id = $1
ORDER BY environment
`

func (q *Queries) ListProjectEnvironments(ctx context.Context, projectID pgtype.UUID) ([]ProjectEnvironment, error) {
	rows, err := q.db.Query(ctx, listProjectEnvironments, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProjectEnvironment
	for rows.Next() {
		var i ProjectEnvironment
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Environment,
			&i.ClusterName,
			&i.Namespace,
			&i.Url,
			&i.Replicas,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
