// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: project_services.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const linkProjectService = `-- name: LinkProjectService :exec
INSERT INTO project_services (project_id, service_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type LinkProjectServiceParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	ServiceID pgtype.UUID `json:"service_id"`
}

func (q *Queries) LinkProjectService(ctx context.Context, arg LinkProjectServiceParams) error {
	_, err := q.db.Exec(ctx, linkProjectService, arg.ProjectID, arg.ServiceID)
	return err
}

const listProjectServices = `-- name: ListProjectServices :many
SELECT project_id, service_id FROM project_services
WHERE project_id = $1
`

func (q *Queries) ListProjectServices(ctx context.Context, projectID pgtype.UUID) ([]ProjectService, error) {
	rows, err := q.db.Query(ctx, listProjectServices, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProjectService
	for rows.Next() {
		var i ProjectService
		if err := rows.Scan(&i.ProjectID, &i.ServiceID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unlinkProjectService = `-- name: UnlinkProjectService :exec
DELETE FROM project_services
WHERE project_id = $1 AND service_id = $2
`

type UnlinkProjectServiceParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	ServiceID pgtype.UUID `json:"service_id"`
}

func (q *Queries) UnlinkProjectService(ctx context.Context, arg UnlinkProjectServiceParams) error {
	_, err := q.db.Exec(ctx, unlinkProjectService, arg.ProjectID, arg.ServiceID)
	return err
}
