// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: project_dependencies.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addProjectDependency = `-- name: AddProjectDependency :one
INSERT INTO project_dependencies (project_id, depends_on_project_id, dependency_type)
VALUES ($1, $2, $3)
RETURNING id, project_id, depends_on_project_id, dependency_type, created_at
`

type AddProjectDependencyParams struct {
	ProjectID          pgtype.UUID `json:"project_id"`
	DependsOnProjectID pgtype.UUID `json:"depends_on_project_id"`
	DependencyType     string      `json:"dependency_type"`
}

func (q *Queries) AddProjectDependency(ctx context.Context, arg AddProjectDependencyParams) (ProjectDependency, error) {
	row := q.db.QueryRow(ctx, addProjectDependency, arg.ProjectID, arg.DependsOnProjectID, arg.DependencyType)
	var i ProjectDependency
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.DependsOnProjectID,
		&i.DependencyType,
		&i.CreatedAt,
	)
	return i, err
}

const listDependentProjects = `-- name: ListDependentProjects :many
SELECT id, project_id, depends_on_project_id, dependency_type, created_at FROM project_dependencies
WHERE depends_on_project_id = $1
ORDER BY created_at
`

// Projects that depend on the given project (impact check before deletion).
func (q *Queries) ListDependentProjects(ctx context.Context, dependsOnProjectID pgtype.UUID) ([]ProjectDependency, error) {
	rows, err := q.db.Query(ctx, listDependentProjects, dependsOnProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProjectDependency
	for rows.Next() {
		var i ProjectDependency
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.DependsOnProjectID,
			&i.DependencyType,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectDependencies = `-- name: ListProjectDependencies :many
SELECT id, project_id, depends_on_project_id, dependency_type, created_at FROM project_dependencies
WHERE project_id = $1
ORDER BY created_at
`

// Projects that the given project depends on.
func (q *Queries) ListProjectDependencies(ctx context.Context, projectID pgtype.UUID) ([]ProjectDependency, error) {
	rows, err := q.db.Query(ctx, listProjectDependencies, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProjectDependency
	for rows.Next() {
		var i ProjectDependency
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.DependsOnProjectID,
			&i.DependencyType,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeProjectDependency = `-- name: RemoveProjectDependency :exec
DELETE FROM project_dependencies
WHERE project_id = $1 AND depends_on_project_id = $2
`

type RemoveProjectDependencyParams struct {
	ProjectID          pgtype.UUID `json:"project_id"`
	DependsOnProjectID pgtype.UUID `json:"depends_on_project_id"`
}

func (q *Queries) RemoveProjectDependency(ctx context.Context, arg RemoveProjectDependencyParams) error {
	_, err := q.db.Exec(ctx, removeProjectDependency, arg.ProjectID, arg.DependsOnProjectID)
	return err
}
