// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	ActivateRepo(ctx context.Context, arg ActivateRepoParams) (Repo, error)
	AddTeamMember(ctx context.Context, arg AddTeamMemberParams) (TeamMember, error)
	CountActiveDBInstances(ctx context.Context) (int64, error)
	CountActiveDeploymentsByInstanceID(ctx context.Context, deploymentInstanceID pgtype.UUID) (int64, error)
	CreateDBInstance(ctx context.Context, arg CreateDBInstanceParams) (DbInstance, error)
	CreateDeployment(ctx context.Context, arg CreateDeploymentParams) (Deployment, error)
	CreateDeploymentInstance(ctx context.Context, arg CreateDeploymentInstanceParams) (Deploymentinstance, error)
	CreateDeploymentRevision(ctx context.Context, arg CreateDeploymentRevisionParams) (Deploymentrevision, error)
	CreateManagedDatabase(ctx context.Context, arg CreateManagedDatabaseParams) (ManagedDatabase, error)
	CreateRegistry(ctx context.Context, arg CreateRegistryParams) (Registry, error)
	CreateRepo(ctx context.Context, arg CreateRepoParams) (Repo, error)
	CreateTeam(ctx context.Context, arg CreateTeamParams) (Team, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteDeployment(ctx context.Context, id pgtype.UUID) (int64, error)
	DeleteRepo(ctx context.Context, id pgtype.UUID) (int64, error)
	DeleteUser(ctx context.Context, id pgtype.UUID) error
	FailRepo(ctx context.Context, arg FailRepoParams) (Repo, error)
	GetActiveTeamMember(ctx context.Context, arg GetActiveTeamMemberParams) (TeamMember, error)
	GetDBInstanceByID(ctx context.Context, id pgtype.UUID) (DbInstance, error)
	GetDBInstanceByName(ctx context.Context, name string) (DbInstance, error)
	GetDeploymentByID(ctx context.Context, id pgtype.UUID) (Deployment, error)
	GetLatestDeploymentRevision(ctx context.Context, deploymentID pgtype.UUID) (Deploymentrevision, error)
	GetLiveDeploymentInstance(ctx context.Context) (Deploymentinstance, error)
	GetManagedDatabaseByID(ctx context.Context, id pgtype.UUID) (ManagedDatabase, error)
	GetManagedDatabaseByName(ctx context.Context, arg GetManagedDatabaseByNameParams) (ManagedDatabase, error)
	GetRegistryByID(ctx context.Context, id pgtype.UUID) (Registry, error)
	GetRegistryByName(ctx context.Context, arg GetRegistryByNameParams) (Registry, error)
	GetRepoByID(ctx context.Context, id pgtype.UUID) (Repo, error)
	GetRepoTemplateBySlug(ctx context.Context, slug string) (RepoTemplate, error)
	GetRoleByName(ctx context.Context, name string) (Role, error)
	GetTeamByID(ctx context.Context, id pgtype.UUID) (Team, error)
	GetTeamBySlug(ctx context.Context, slug string) (Team, error)
	GetTotalAllocatedMB(ctx context.Context) (int64, error)
	GetTotalAllocatedMBByInstanceID(ctx context.Context, dbInstanceID pgtype.UUID) (int64, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	ListActiveManagedDatabasesByInstanceID(ctx context.Context, dbInstanceID pgtype.UUID) ([]ManagedDatabase, error)
	ListDBInstances(ctx context.Context) ([]DbInstance, error)
	ListDeployments(ctx context.Context) ([]Deployment, error)
	ListLanguages(ctx context.Context) ([]Language, error)
	ListManagedDatabases(ctx context.Context) ([]ManagedDatabase, error)
	ListManagedDatabasesByInstanceID(ctx context.Context, dbInstanceID pgtype.UUID) ([]ManagedDatabase, error)
	ListRegistries(ctx context.Context) ([]Registry, error)
	ListRegistryProviders(ctx context.Context) ([]RegistryProvider, error)
	ListRepoProviders(ctx context.Context) ([]RepoProvider, error)
	ListRepoTemplates(ctx context.Context) ([]RepoTemplate, error)
	ListRepos(ctx context.Context) ([]Repo, error)
	ListTeamMembers(ctx context.Context, teamID pgtype.UUID) ([]TeamMember, error)
	ListTeams(ctx context.Context) ([]Team, error)
	ListUsers(ctx context.Context) ([]User, error)
	MarkDBInstanceContainerStatus(ctx context.Context, arg MarkDBInstanceContainerStatusParams) (int64, error)
	MarkDBInstanceProvisioned(ctx context.Context, arg MarkDBInstanceProvisionedParams) (DbInstance, error)
	MarkDBInstanceStatus(ctx context.Context, arg MarkDBInstanceStatusParams) (int64, error)
	MarkDeploymentDeploying(ctx context.Context, id pgtype.UUID) (Deployment, error)
	MarkDeploymentInstanceProvisioned(ctx context.Context, arg MarkDeploymentInstanceProvisionedParams) (Deploymentinstance, error)
	MarkDeploymentInstanceStatus(ctx context.Context, arg MarkDeploymentInstanceStatusParams) (int64, error)
	MarkDeploymentInstanceTerminated(ctx context.Context, id pgtype.UUID) (int64, error)
	MarkDeploymentStatus(ctx context.Context, arg MarkDeploymentStatusParams) (int64, error)
	MarkManagedDatabaseStatus(ctx context.Context, arg MarkManagedDatabaseStatusParams) (int64, error)
	MarkRepoCreating(ctx context.Context, id pgtype.UUID) (Repo, error)
	RemoveTeamMember(ctx context.Context, id pgtype.UUID) error
	SoftDeleteDBInstance(ctx context.Context, id pgtype.UUID) (int64, error)
	SoftDeleteManagedDatabase(ctx context.Context, id pgtype.UUID) (int64, error)
	SoftDeleteManagedDatabasesByInstanceID(ctx context.Context, dbInstanceID pgtype.UUID) (int64, error)
	SoftDeleteRegistry(ctx context.Context, id pgtype.UUID) (int64, error)
	UpdateLastLogin(ctx context.Context, id pgtype.UUID) error
	UpdateRegistry(ctx context.Context, arg UpdateRegistryParams) (Registry, error)
	UpdateRepo(ctx context.Context, arg UpdateRepoParams) (Repo, error)
}

var _ Querier = (*Queries)(nil)
