// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: registries.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRegistry = `-- name: CreateRegistry :one
INSERT INTO registries (
    name, description, provider_id, namespace, registry_url, visibility, status, created_by
) VALUES (
    $1, $2, $3, $4, $5, $6, 'active', $7
)
RETURNING id, name, description, provider_id, namespace, registry_url, visibility, status, created_by, created_at, updated_at, deleted_at
`

type CreateRegistryParams struct {
	Name        string      `json:"name"`
	Description string      `json:"description"`
	ProviderID  int16       `json:"provider_id"`
	Namespace   string      `json:"namespace"`
	RegistryUrl pgtype.Text `json:"registry_url"`
	Visibility  string      `json:"visibility"`
	CreatedBy   pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreateRegistry(ctx context.Context, arg CreateRegistryParams) (Registry, error) {
	row := q.db.QueryRow(ctx, createRegistry,
		arg.Name,
		arg.Description,
		arg.ProviderID,
		arg.Namespace,
		arg.RegistryUrl,
		arg.Visibility,
		arg.CreatedBy,
	)
	var i Registry
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.ProviderID,
		&i.Namespace,
		&i.RegistryUrl,
		&i.Visibility,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getRegistryByID = `-- name: GetRegistryByID :one
SELECT id, name, description, provider_id, namespace, registry_url, visibility, status, created_by, created_at, updated_at, deleted_at FROM registries
WHERE id = $1 AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetRegistryByID(ctx context.Context, id pgtype.UUID) (Registry, error) {
	row := q.db.QueryRow(ctx, getRegistryByID, id)
	var i Registry
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.ProviderID,
		&i.Namespace,
		&i.RegistryUrl,
		&i.Visibility,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getRegistryByName = `-- name: GetRegistryByName :one
SELECT id, name, description, provider_id, namespace, registry_url, visibility, status, created_by, created_at, updated_at, deleted_at FROM registries
WHERE provider_id = $1 AND namespace = $2 AND name = $3 AND deleted_at IS NULL
LIMIT 1
`

type GetRegistryByNameParams struct {
	ProviderID int16  `json:"provider_id"`
	Namespace  string `json:"namespace"`
	Name       string `json:"name"`
}

func (q *Queries) GetRegistryByName(ctx context.Context, arg GetRegistryByNameParams) (Registry, error) {
	row := q.db.QueryRow(ctx, getRegistryByName, arg.ProviderID, arg.Namespace, arg.Name)
	var i Registry
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.ProviderID,
		&i.Namespace,
		&i.RegistryUrl,
		&i.Visibility,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listRegistries = `-- name: ListRegistries :many
SELECT id, name, description, provider_id, namespace, registry_url, visibility, status, created_by, created_at, updated_at, deleted_at FROM registries
WHERE deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListRegistries(ctx context.Context) ([]Registry, error) {
	rows, err := q.db.Query(ctx, listRegistries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Registry
	for rows.Next() {
		var i Registry
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.ProviderID,
			&i.Namespace,
			&i.RegistryUrl,
			&i.Visibility,
			&i.Status,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteRegistry = `-- name: SoftDeleteRegistry :execrows
UPDATE registries
SET deleted_at = now(), status = 'archived', updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteRegistry(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteRegistry, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateRegistry = `-- name: UpdateRegistry :one
UPDATE registries
SET description = $2,
    visibility = $3,
    status = $4,
    updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, name, description, provider_id, namespace, registry_url, visibility, status, created_by, created_at, updated_at, deleted_at
`

type UpdateRegistryParams struct {
	ID          pgtype.UUID `json:"id"`
	Description string      `json:"description"`
	Visibility  string      `json:"visibility"`
	Status      string      `json:"status"`
}

func (q *Queries) UpdateRegistry(ctx context.Context, arg UpdateRegistryParams) (Registry, error) {
	row := q.db.QueryRow(ctx, updateRegistry,
		arg.ID,
		arg.Description,
		arg.Visibility,
		arg.Status,
	)
	var i Registry
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.ProviderID,
		&i.Namespace,
		&i.RegistryUrl,
		&i.Visibility,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
