// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: repos.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const activateRepo = `-- name: ActivateRepo :one
UPDATE repos
SET full_name = $2,
    owner = $3,
    external_id = $4,
    url = $5,
    clone_url_ssh = $6,
    clone_url_https = $7,
    default_branch = $8,
    visibility = $9,
    status = 'active',
    error_message = NULL,
    updated_at = now()
WHERE id = $1
RETURNING id, name, full_name, owner, provider_id, external_id, url, clone_url_ssh, clone_url_https, default_branch, visibility, template_used, status, error_message, created_by, created_at, updated_at
`

type ActivateRepoParams struct {
	ID            pgtype.UUID `json:"id"`
	FullName      pgtype.Text `json:"full_name"`
	Owner         string      `json:"owner"`
	ExternalID    pgtype.Text `json:"external_id"`
	Url           pgtype.Text `json:"url"`
	CloneUrlSsh   pgtype.Text `json:"clone_url_ssh"`
	CloneUrlHttps pgtype.Text `json:"clone_url_https"`
	DefaultBranch string      `json:"default_branch"`
	Visibility    string      `json:"visibility"`
}

func (q *Queries) ActivateRepo(ctx context.Context, arg ActivateRepoParams) (Repo, error) {
	row := q.db.QueryRow(ctx, activateRepo,
		arg.ID,
		arg.FullName,
		arg.Owner,
		arg.ExternalID,
		arg.Url,
		arg.CloneUrlSsh,
		arg.CloneUrlHttps,
		arg.DefaultBranch,
		arg.Visibility,
	)
	var i Repo
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.FullName,
		&i.Owner,
		&i.ProviderID,
		&i.ExternalID,
		&i.Url,
		&i.CloneUrlSsh,
		&i.CloneUrlHttps,
		&i.DefaultBranch,
		&i.Visibility,
		&i.TemplateUsed,
		&i.Status,
		&i.ErrorMessage,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createRepo = `-- name: CreateRepo :one
INSERT INTO repos (
    name, owner, provider_id, visibility, created_by, status
) VALUES (
    $1, $2, $3, $4, $5, 'pending'
)
RETURNING id, name, full_name, owner, provider_id, external_id, url, clone_url_ssh, clone_url_https, default_branch, visibility, template_used, status, error_message, created_by, created_at, updated_at
`

type CreateRepoParams struct {
	Name       string      `json:"name"`
	Owner      string      `json:"owner"`
	ProviderID int16       `json:"provider_id"`
	Visibility string      `json:"visibility"`
	CreatedBy  pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreateRepo(ctx context.Context, arg CreateRepoParams) (Repo, error) {
	row := q.db.QueryRow(ctx, createRepo,
		arg.Name,
		arg.Owner,
		arg.ProviderID,
		arg.Visibility,
		arg.CreatedBy,
	)
	var i Repo
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.FullName,
		&i.Owner,
		&i.ProviderID,
		&i.ExternalID,
		&i.Url,
		&i.CloneUrlSsh,
		&i.CloneUrlHttps,
		&i.DefaultBranch,
		&i.Visibility,
		&i.TemplateUsed,
		&i.Status,
		&i.ErrorMessage,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteRepo = `-- name: DeleteRepo :execrows
DELETE FROM repos
WHERE id = $1
`

func (q *Queries) DeleteRepo(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRepo, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const failRepo = `-- name: FailRepo :one
UPDATE repos
SET status = 'failed', error_message = $2, updated_at = now()
WHERE id = $1
RETURNING id, name, full_name, owner, provider_id, external_id, url, clone_url_ssh, clone_url_https, default_branch, visibility, template_used, status, error_message, created_by, created_at, updated_at
`

type FailRepoParams struct {
	ID           pgtype.UUID `json:"id"`
	ErrorMessage pgtype.Text `json:"error_message"`
}

func (q *Queries) FailRepo(ctx context.Context, arg FailRepoParams) (Repo, error) {
	row := q.db.QueryRow(ctx, failRepo, arg.ID, arg.ErrorMessage)
	var i Repo
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.FullName,
		&i.Owner,
		&i.ProviderID,
		&i.ExternalID,
		&i.Url,
		&i.CloneUrlSsh,
		&i.CloneUrlHttps,
		&i.DefaultBranch,
		&i.Visibility,
		&i.TemplateUsed,
		&i.Status,
		&i.ErrorMessage,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRepoByID = `-- name: GetRepoByID :one
SELECT id, name, full_name, owner, provider_id, external_id, url, clone_url_ssh, clone_url_https, default_branch, visibility, template_used, status, error_message, created_by, created_at, updated_at FROM repos
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetRepoByID(ctx context.Context, id pgtype.UUID) (Repo, error) {
	row := q.db.QueryRow(ctx, getRepoByID, id)
	var i Repo
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.FullName,
		&i.Owner,
		&i.ProviderID,
		&i.ExternalID,
		&i.Url,
		&i.CloneUrlSsh,
		&i.CloneUrlHttps,
		&i.DefaultBranch,
		&i.Visibility,
		&i.TemplateUsed,
		&i.Status,
		&i.ErrorMessage,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRepos = `-- name: ListRepos :many
SELECT id, name, full_name, owner, provider_id, external_id, url, clone_url_ssh, clone_url_https, default_branch, visibility, template_used, status, error_message, created_by, created_at, updated_at FROM repos
ORDER BY created_at DESC
`

func (q *Queries) ListRepos(ctx context.Context) ([]Repo, error) {
	rows, err := q.db.Query(ctx, listRepos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Repo
	for rows.Next() {
		var i Repo
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.FullName,
			&i.Owner,
			&i.ProviderID,
			&i.ExternalID,
			&i.Url,
			&i.CloneUrlSsh,
			&i.CloneUrlHttps,
			&i.DefaultBranch,
			&i.Visibility,
			&i.TemplateUsed,
			&i.Status,
			&i.ErrorMessage,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markRepoCreating = `-- name: MarkRepoCreating :one
UPDATE repos
SET status = 'creating', error_message = NULL, updated_at = now()
WHERE id = $1
RETURNING id, name, full_name, owner, provider_id, external_id, url, clone_url_ssh, clone_url_https, default_branch, visibility, template_used, status, error_message, created_by, created_at, updated_at
`

func (q *Queries) MarkRepoCreating(ctx context.Context, id pgtype.UUID) (Repo, error) {
	row := q.db.QueryRow(ctx, markRepoCreating, id)
	var i Repo
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.FullName,
		&i.Owner,
		&i.ProviderID,
		&i.ExternalID,
		&i.Url,
		&i.CloneUrlSsh,
		&i.CloneUrlHttps,
		&i.DefaultBranch,
		&i.Visibility,
		&i.TemplateUsed,
		&i.Status,
		&i.ErrorMessage,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateRepo = `-- name: UpdateRepo :one
UPDATE repos
SET name = $2,
    default_branch = $3,
    visibility = $4,
    template_used = $5,
    status = $6,
    updated_at = now()
WHERE id = $1
RETURNING id, name, full_name, owner, provider_id, external_id, url, clone_url_ssh, clone_url_https, default_branch, visibility, template_used, status, error_message, created_by, created_at, updated_at
`

type UpdateRepoParams struct {
	ID            pgtype.UUID `json:"id"`
	Name          string      `json:"name"`
	DefaultBranch string      `json:"default_branch"`
	Visibility    string      `json:"visibility"`
	TemplateUsed  pgtype.Text `json:"template_used"`
	Status        string      `json:"status"`
}

func (q *Queries) UpdateRepo(ctx context.Context, arg UpdateRepoParams) (Repo, error) {
	row := q.db.QueryRow(ctx, updateRepo,
		arg.ID,
		arg.Name,
		arg.DefaultBranch,
		arg.Visibility,
		arg.TemplateUsed,
		arg.Status,
	)
	var i Repo
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.FullName,
		&i.Owner,
		&i.ProviderID,
		&i.ExternalID,
		&i.Url,
		&i.CloneUrlSsh,
		&i.CloneUrlHttps,
		&i.DefaultBranch,
		&i.Visibility,
		&i.TemplateUsed,
		&i.Status,
		&i.ErrorMessage,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
