// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: service_tags.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addServiceTag = `-- name: AddServiceTag :exec
INSERT INTO service_tags (service_id, tag)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddServiceTagParams struct {
	ServiceID pgtype.UUID `json:"service_id"`
	Tag       string      `json:"tag"`
}

func (q *Queries) AddServiceTag(ctx context.Context, arg AddServiceTagParams) error {
	_, err := q.db.Exec(ctx, addServiceTag, arg.ServiceID, arg.Tag)
	return err
}

const listServiceTags = `-- name: ListServiceTags :many
SELECT service_id, tag FROM service_tags
WHERE service_id = $1
ORDER BY tag
`

func (q *Queries) ListServiceTags(ctx context.Context, serviceID pgtype.UUID) ([]ServiceTag, error) {
	rows, err := q.db.Query(ctx, listServiceTags, serviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ServiceTag
	for rows.Next() {
		var i ServiceTag
		if err := rows.Scan(&i.ServiceID, &i.Tag); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeServiceTag = `-- name: RemoveServiceTag :exec
DELETE FROM service_tags
WHERE service_id = $1 AND tag = $2
`

type RemoveServiceTagParams struct {
	ServiceID pgtype.UUID `json:"service_id"`
	Tag       string      `json:"tag"`
}

func (q *Queries) RemoveServiceTag(ctx context.Context, arg RemoveServiceTagParams) error {
	_, err := q.db.Exec(ctx, removeServiceTag, arg.ServiceID, arg.Tag)
	return err
}
