// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: service_dependencies.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addServiceDependency = `-- name: AddServiceDependency :one
INSERT INTO service_dependencies (service_id, depends_on_service_id, dependency_type, is_critical)
VALUES ($1, $2, $3, $4)
RETURNING service_id, depends_on_service_id, dependency_type, is_critical
`

type AddServiceDependencyParams struct {
	ServiceID          pgtype.UUID `json:"service_id"`
	DependsOnServiceID pgtype.UUID `json:"depends_on_service_id"`
	DependencyType     pgtype.Text `json:"dependency_type"`
	IsCritical         bool        `json:"is_critical"`
}

func (q *Queries) AddServiceDependency(ctx context.Context, arg AddServiceDependencyParams) (ServiceDependency, error) {
	row := q.db.QueryRow(ctx, addServiceDependency,
		arg.ServiceID,
		arg.DependsOnServiceID,
		arg.DependencyType,
		arg.IsCritical,
	)
	var i ServiceDependency
	err := row.Scan(
		&i.ServiceID,
		&i.DependsOnServiceID,
		&i.DependencyType,
		&i.IsCritical,
	)
	return i, err
}

const listDependentServices = `-- name: ListDependentServices :many
SELECT service_id, depends_on_service_id, dependency_type, is_critical FROM service_dependencies
WHERE depends_on_service_id = $1
`

// Services that depend on the given service (impact check before deletion).
func (q *Queries) ListDependentServices(ctx context.Context, dependsOnServiceID pgtype.UUID) ([]ServiceDependency, error) {
	rows, err := q.db.Query(ctx, listDependentServices, dependsOnServiceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ServiceDependency
	for rows.Next() {
		var i ServiceDependency
		if err := rows.Scan(
			&i.ServiceID,
			&i.DependsOnServiceID,
			&i.DependencyType,
			&i.IsCritical,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServiceDependencies = `-- name: ListServiceDependencies :many
SELECT service_id, depends_on_service_id, dependency_type, is_critical FROM service_dependencies
WHERE service_id = $1
`

// Services that the given service depends on.
func (q *Queries) ListServiceDependencies(ctx context.Context, serviceID pgtype.UUID) ([]ServiceDependency, error) {
	rows, err := q.db.Query(ctx, listServiceDependencies, serviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ServiceDependency
	for rows.Next() {
		var i ServiceDependency
		if err := rows.Scan(
			&i.ServiceID,
			&i.DependsOnServiceID,
			&i.DependencyType,
			&i.IsCritical,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeServiceDependency = `-- name: RemoveServiceDependency :exec
DELETE FROM service_dependencies
WHERE service_id = $1 AND depends_on_service_id = $2
`

type RemoveServiceDependencyParams struct {
	ServiceID          pgtype.UUID `json:"service_id"`
	DependsOnServiceID pgtype.UUID `json:"depends_on_service_id"`
}

func (q *Queries) RemoveServiceDependency(ctx context.Context, arg RemoveServiceDependencyParams) error {
	_, err := q.db.Exec(ctx, removeServiceDependency, arg.ServiceID, arg.DependsOnServiceID)
	return err
}
