// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: service_environments.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addServiceEnvironment = `-- name: AddServiceEnvironment :one
INSERT INTO service_environments (
    service_id, environment, cluster_name, namespace,
    replicas_min, replicas_max, cpu_request, memory_request, current_image_tag, url
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8, $9, $10
)
RETURNING id, service_id, environment, cluster_name, namespace, replicas_min, replicas_max, cpu_request, memory_request, current_image_tag, url
`

type AddServiceEnvironmentParams struct {
	ServiceID       pgtype.UUID `json:"service_id"`
	Environment     string      `json:"environment"`
	ClusterName     pgtype.Text `json:"cluster_name"`
	Namespace       pgtype.Text `json:"namespace"`
	ReplicasMin     int32       `json:"replicas_min"`
	ReplicasMax     int32       `json:"replicas_max"`
	CpuRequest      pgtype.Text `json:"cpu_request"`
	MemoryRequest   pgtype.Text `json:"memory_request"`
	CurrentImageTag pgtype.Text `json:"current_image_tag"`
	Url             pgtype.Text `json:"url"`
}

func (q *Queries) AddServiceEnvironment(ctx context.Context, arg AddServiceEnvironmentParams) (ServiceEnvironment, error) {
	row := q.db.QueryRow(ctx, addServiceEnvironment,
		arg.ServiceID,
		arg.Environment,
		arg.ClusterName,
		arg.Namespace,
		arg.ReplicasMin,
		arg.ReplicasMax,
		arg.CpuRequest,
		arg.MemoryRequest,
		arg.CurrentImageTag,
		arg.Url,
	)
	var i ServiceEnvironment
	err := row.Scan(
		&i.ID,
		&i.ServiceID,
		&i.Environment,
		&i.ClusterName,
		&i.Namespace,
		&i.ReplicasMin,
		&i.ReplicasMax,
		&i.CpuRequest,
		&i.MemoryRequest,
		&i.CurrentImageTag,
		&i.Url,
	)
	return i, err
}

const getServiceEnvironment = `-- name: GetServiceEnvironment :one
SELECT id, service_id, environment, cluster_name, namespace, replicas_min, replicas_max, cpu_request, memory_request, current_image_tag, url FROM service_environments
WHERE service_id = $1 AND environment = $2
LIMIT 1
`

type GetServiceEnvironmentParams struct {
	ServiceID   pgtype.UUID `json:"service_id"`
	Environment string      `json:"environment"`
}

func (q *Queries) GetServiceEnvironment(ctx context.Context, arg GetServiceEnvironmentParams) (ServiceEnvironment, error) {
	row := q.db.QueryRow(ctx, getServiceEnvironment, arg.ServiceID, arg.Environment)
	var i ServiceEnvironment
	err := row.Scan(
		&i.ID,
		&i.ServiceID,
		&i.Environment,
		&i.ClusterName,
		&i.Namespace,
		&i.ReplicasMin,
		&i.ReplicasMax,
		&i.CpuRequest,
		&i.MemoryRequest,
		&i.CurrentImageTag,
		&i.Url,
	)
	return i, err
}

const listServiceEnvironments = `-- name: ListServiceEnvironments :many
SELECT id, service_id, environment, cluster_name, namespace, replicas_min, replicas_max, cpu_request, memory_request, current_image_tag, url FROM service_environments
WHERE service_id = $1
ORDER BY environment
`

func (q *Queries) ListServiceEnvironments(ctx context.Context, serviceID pgtype.UUID) ([]ServiceEnvironment, error) {
	rows, err := q.db.Query(ctx, listServiceEnvironments, serviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ServiceEnvironment
	for rows.Next() {
		var i ServiceEnvironment
		if err := rows.Scan(
			&i.ID,
			&i.ServiceID,
			&i.Environment,
			&i.ClusterName,
			&i.Namespace,
			&i.ReplicasMin,
			&i.ReplicasMax,
			&i.CpuRequest,
			&i.MemoryRequest,
			&i.CurrentImageTag,
			&i.Url,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
