// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: services.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createService = `-- name: CreateService :one
INSERT INTO services (
    name, slug, description, service_type_id, lifecycle_id, tier_id,
    project_id, owner_team_id, tech_lead_id,
    repo_url, repo_provider_id, default_branch, language_id, framework,
    dockerfile_path, registry_image, ci_pipeline_url,
    gitops_repo_path, k8s_resource_kind,
    port, health_check_path, internal_url, external_url,
    api_spec_url, dashboard_url, runbook_url, slo_target
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9,
    $10, $11, $12, $13, $14,
    $15, $16, $17,
    $18, $19,
    $20, $21, $22, $23,
    $24, $25, $26, $27
)
RETURNING id, name, slug, description, service_type_id, lifecycle_id, tier_id, project_id, owner_team_id, tech_lead_id, repo_url, repo_provider_id, default_branch, language_id, framework, dockerfile_path, registry_image, ci_pipeline_url, gitops_repo_path, k8s_resource_kind, port, health_check_path, internal_url, external_url, api_spec_url, dashboard_url, runbook_url, slo_target, is_active, created_at, updated_at
`

type CreateServiceParams struct {
	Name            string         `json:"name"`
	Slug            string         `json:"slug"`
	Description     pgtype.Text    `json:"description"`
	ServiceTypeID   int16          `json:"service_type_id"`
	LifecycleID     pgtype.Int2    `json:"lifecycle_id"`
	TierID          pgtype.Int2    `json:"tier_id"`
	ProjectID       pgtype.UUID    `json:"project_id"`
	OwnerTeamID     pgtype.UUID    `json:"owner_team_id"`
	TechLeadID      pgtype.UUID    `json:"tech_lead_id"`
	RepoUrl         string         `json:"repo_url"`
	RepoProviderID  pgtype.Int2    `json:"repo_provider_id"`
	DefaultBranch   string         `json:"default_branch"`
	LanguageID      pgtype.Int2    `json:"language_id"`
	Framework       pgtype.Text    `json:"framework"`
	DockerfilePath  string         `json:"dockerfile_path"`
	RegistryImage   pgtype.Text    `json:"registry_image"`
	CiPipelineUrl   pgtype.Text    `json:"ci_pipeline_url"`
	GitopsRepoPath  pgtype.Text    `json:"gitops_repo_path"`
	K8sResourceKind string         `json:"k8s_resource_kind"`
	Port            pgtype.Int4    `json:"port"`
	HealthCheckPath string         `json:"health_check_path"`
	InternalUrl     pgtype.Text    `json:"internal_url"`
	ExternalUrl     pgtype.Text    `json:"external_url"`
	ApiSpecUrl      pgtype.Text    `json:"api_spec_url"`
	DashboardUrl    pgtype.Text    `json:"dashboard_url"`
	RunbookUrl      pgtype.Text    `json:"runbook_url"`
	SloTarget       pgtype.Numeric `json:"slo_target"`
}

func (q *Queries) CreateService(ctx context.Context, arg CreateServiceParams) (Service, error) {
	row := q.db.QueryRow(ctx, createService,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.ServiceTypeID,
		arg.LifecycleID,
		arg.TierID,
		arg.ProjectID,
		arg.OwnerTeamID,
		arg.TechLeadID,
		arg.RepoUrl,
		arg.RepoProviderID,
		arg.DefaultBranch,
		arg.LanguageID,
		arg.Framework,
		arg.DockerfilePath,
		arg.RegistryImage,
		arg.CiPipelineUrl,
		arg.GitopsRepoPath,
		arg.K8sResourceKind,
		arg.Port,
		arg.HealthCheckPath,
		arg.InternalUrl,
		arg.ExternalUrl,
		arg.ApiSpecUrl,
		arg.DashboardUrl,
		arg.RunbookUrl,
		arg.SloTarget,
	)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.ServiceTypeID,
		&i.LifecycleID,
		&i.TierID,
		&i.ProjectID,
		&i.OwnerTeamID,
		&i.TechLeadID,
		&i.RepoUrl,
		&i.RepoProviderID,
		&i.DefaultBranch,
		&i.LanguageID,
		&i.Framework,
		&i.DockerfilePath,
		&i.RegistryImage,
		&i.CiPipelineUrl,
		&i.GitopsRepoPath,
		&i.K8sResourceKind,
		&i.Port,
		&i.HealthCheckPath,
		&i.InternalUrl,
		&i.ExternalUrl,
		&i.ApiSpecUrl,
		&i.DashboardUrl,
		&i.RunbookUrl,
		&i.SloTarget,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getServiceByID = `-- name: GetServiceByID :one
SELECT id, name, slug, description, service_type_id, lifecycle_id, tier_id, project_id, owner_team_id, tech_lead_id, repo_url, repo_provider_id, default_branch, language_id, framework, dockerfile_path, registry_image, ci_pipeline_url, gitops_repo_path, k8s_resource_kind, port, health_check_path, internal_url, external_url, api_spec_url, dashboard_url, runbook_url, slo_target, is_active, created_at, updated_at FROM services
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetServiceByID(ctx context.Context, id pgtype.UUID) (Service, error) {
	row := q.db.QueryRow(ctx, getServiceByID, id)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.ServiceTypeID,
		&i.LifecycleID,
		&i.TierID,
		&i.ProjectID,
		&i.OwnerTeamID,
		&i.TechLeadID,
		&i.RepoUrl,
		&i.RepoProviderID,
		&i.DefaultBranch,
		&i.LanguageID,
		&i.Framework,
		&i.DockerfilePath,
		&i.RegistryImage,
		&i.CiPipelineUrl,
		&i.GitopsRepoPath,
		&i.K8sResourceKind,
		&i.Port,
		&i.HealthCheckPath,
		&i.InternalUrl,
		&i.ExternalUrl,
		&i.ApiSpecUrl,
		&i.DashboardUrl,
		&i.RunbookUrl,
		&i.SloTarget,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getServiceBySlug = `-- name: GetServiceBySlug :one
SELECT id, name, slug, description, service_type_id, lifecycle_id, tier_id, project_id, owner_team_id, tech_lead_id, repo_url, repo_provider_id, default_branch, language_id, framework, dockerfile_path, registry_image, ci_pipeline_url, gitops_repo_path, k8s_resource_kind, port, health_check_path, internal_url, external_url, api_spec_url, dashboard_url, runbook_url, slo_target, is_active, created_at, updated_at FROM services
WHERE slug = $1
LIMIT 1
`

func (q *Queries) GetServiceBySlug(ctx context.Context, slug string) (Service, error) {
	row := q.db.QueryRow(ctx, getServiceBySlug, slug)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.ServiceTypeID,
		&i.LifecycleID,
		&i.TierID,
		&i.ProjectID,
		&i.OwnerTeamID,
		&i.TechLeadID,
		&i.RepoUrl,
		&i.RepoProviderID,
		&i.DefaultBranch,
		&i.LanguageID,
		&i.Framework,
		&i.DockerfilePath,
		&i.RegistryImage,
		&i.CiPipelineUrl,
		&i.GitopsRepoPath,
		&i.K8sResourceKind,
		&i.Port,
		&i.HealthCheckPath,
		&i.InternalUrl,
		&i.ExternalUrl,
		&i.ApiSpecUrl,
		&i.DashboardUrl,
		&i.RunbookUrl,
		&i.SloTarget,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listServices = `-- name: ListServices :many
SELECT id, name, slug, description, service_type_id, lifecycle_id, tier_id, project_id, owner_team_id, tech_lead_id, repo_url, repo_provider_id, default_branch, language_id, framework, dockerfile_path, registry_image, ci_pipeline_url, gitops_repo_path, k8s_resource_kind, port, health_check_path, internal_url, external_url, api_spec_url, dashboard_url, runbook_url, slo_target, is_active, created_at, updated_at FROM services
ORDER BY created_at
`

func (q *Queries) ListServices(ctx context.Context) ([]Service, error) {
	rows, err := q.db.Query(ctx, listServices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Service
	for rows.Next() {
		var i Service
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.ServiceTypeID,
			&i.LifecycleID,
			&i.TierID,
			&i.ProjectID,
			&i.OwnerTeamID,
			&i.TechLeadID,
			&i.RepoUrl,
			&i.RepoProviderID,
			&i.DefaultBranch,
			&i.LanguageID,
			&i.Framework,
			&i.DockerfilePath,
			&i.RegistryImage,
			&i.CiPipelineUrl,
			&i.GitopsRepoPath,
			&i.K8sResourceKind,
			&i.Port,
			&i.HealthCheckPath,
			&i.InternalUrl,
			&i.ExternalUrl,
			&i.ApiSpecUrl,
			&i.DashboardUrl,
			&i.RunbookUrl,
			&i.SloTarget,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServicesByProject = `-- name: ListServicesByProject :many
SELECT id, name, slug, description, service_type_id, lifecycle_id, tier_id, project_id, owner_team_id, tech_lead_id, repo_url, repo_provider_id, default_branch, language_id, framework, dockerfile_path, registry_image, ci_pipeline_url, gitops_repo_path, k8s_resource_kind, port, health_check_path, internal_url, external_url, api_spec_url, dashboard_url, runbook_url, slo_target, is_active, created_at, updated_at FROM services
WHERE project_id = $1
ORDER BY created_at
`

func (q *Queries) ListServicesByProject(ctx context.Context, projectID pgtype.UUID) ([]Service, error) {
	rows, err := q.db.Query(ctx, listServicesByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Service
	for rows.Next() {
		var i Service
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.ServiceTypeID,
			&i.LifecycleID,
			&i.TierID,
			&i.ProjectID,
			&i.OwnerTeamID,
			&i.TechLeadID,
			&i.RepoUrl,
			&i.RepoProviderID,
			&i.DefaultBranch,
			&i.LanguageID,
			&i.Framework,
			&i.DockerfilePath,
			&i.RegistryImage,
			&i.CiPipelineUrl,
			&i.GitopsRepoPath,
			&i.K8sResourceKind,
			&i.Port,
			&i.HealthCheckPath,
			&i.InternalUrl,
			&i.ExternalUrl,
			&i.ApiSpecUrl,
			&i.DashboardUrl,
			&i.RunbookUrl,
			&i.SloTarget,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
