// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: team_members.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addTeamMember = `-- name: AddTeamMember :one
INSERT INTO team_members (team_id, user_id, role_in_team, is_primary)
VALUES ($1, $2, $3, $4)
RETURNING id, team_id, user_id, role_in_team, is_primary, joined_at, left_at, created_at, updated_at
`

type AddTeamMemberParams struct {
	TeamID     pgtype.UUID `json:"team_id"`
	UserID     pgtype.UUID `json:"user_id"`
	RoleInTeam string      `json:"role_in_team"`
	IsPrimary  bool        `json:"is_primary"`
}

func (q *Queries) AddTeamMember(ctx context.Context, arg AddTeamMemberParams) (TeamMember, error) {
	row := q.db.QueryRow(ctx, addTeamMember,
		arg.TeamID,
		arg.UserID,
		arg.RoleInTeam,
		arg.IsPrimary,
	)
	var i TeamMember
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.UserID,
		&i.RoleInTeam,
		&i.IsPrimary,
		&i.JoinedAt,
		&i.LeftAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveTeamMember = `-- name: GetActiveTeamMember :one
SELECT id, team_id, user_id, role_in_team, is_primary, joined_at, left_at, created_at, updated_at FROM team_members
WHERE team_id = $1 AND user_id = $2 AND left_at IS NULL
LIMIT 1
`

type GetActiveTeamMemberParams struct {
	TeamID pgtype.UUID `json:"team_id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetActiveTeamMember(ctx context.Context, arg GetActiveTeamMemberParams) (TeamMember, error) {
	row := q.db.QueryRow(ctx, getActiveTeamMember, arg.TeamID, arg.UserID)
	var i TeamMember
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.UserID,
		&i.RoleInTeam,
		&i.IsPrimary,
		&i.JoinedAt,
		&i.LeftAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTeamMembers = `-- name: ListTeamMembers :many
SELECT id, team_id, user_id, role_in_team, is_primary, joined_at, left_at, created_at, updated_at FROM team_members
WHERE team_id = $1 AND left_at IS NULL
ORDER BY joined_at
`

func (q *Queries) ListTeamMembers(ctx context.Context, teamID pgtype.UUID) ([]TeamMember, error) {
	rows, err := q.db.Query(ctx, listTeamMembers, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TeamMember
	for rows.Next() {
		var i TeamMember
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.UserID,
			&i.RoleInTeam,
			&i.IsPrimary,
			&i.JoinedAt,
			&i.LeftAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeTeamMember = `-- name: RemoveTeamMember :exec
UPDATE team_members
SET left_at = now(), updated_at = now()
WHERE id = $1
`

func (q *Queries) RemoveTeamMember(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, removeTeamMember, id)
	return err
}
