// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: team_members.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addTeamMember = `-- name: AddTeamMember :one
INSERT INTO team_members (team_id, user_id, role_in_team)
VALUES ($1, $2, $3)
RETURNING team_id, user_id, role_in_team, joined_at, left_at
`

type AddTeamMemberParams struct {
	TeamID     pgtype.UUID `json:"team_id"`
	UserID     pgtype.UUID `json:"user_id"`
	RoleInTeam string      `json:"role_in_team"`
}

func (q *Queries) AddTeamMember(ctx context.Context, arg AddTeamMemberParams) (TeamMember, error) {
	row := q.db.QueryRow(ctx, addTeamMember, arg.TeamID, arg.UserID, arg.RoleInTeam)
	var i TeamMember
	err := row.Scan(
		&i.TeamID,
		&i.UserID,
		&i.RoleInTeam,
		&i.JoinedAt,
		&i.LeftAt,
	)
	return i, err
}

const getTeamMember = `-- name: GetTeamMember :one
SELECT team_id, user_id, role_in_team, joined_at, left_at FROM team_members
WHERE team_id = $1 AND user_id = $2
LIMIT 1
`

type GetTeamMemberParams struct {
	TeamID pgtype.UUID `json:"team_id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetTeamMember(ctx context.Context, arg GetTeamMemberParams) (TeamMember, error) {
	row := q.db.QueryRow(ctx, getTeamMember, arg.TeamID, arg.UserID)
	var i TeamMember
	err := row.Scan(
		&i.TeamID,
		&i.UserID,
		&i.RoleInTeam,
		&i.JoinedAt,
		&i.LeftAt,
	)
	return i, err
}

const listTeamMembers = `-- name: ListTeamMembers :many
SELECT team_id, user_id, role_in_team, joined_at, left_at FROM team_members
WHERE team_id = $1 AND left_at IS NULL
ORDER BY joined_at
`

func (q *Queries) ListTeamMembers(ctx context.Context, teamID pgtype.UUID) ([]TeamMember, error) {
	rows, err := q.db.Query(ctx, listTeamMembers, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TeamMember
	for rows.Next() {
		var i TeamMember
		if err := rows.Scan(
			&i.TeamID,
			&i.UserID,
			&i.RoleInTeam,
			&i.JoinedAt,
			&i.LeftAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeTeamMember = `-- name: RemoveTeamMember :exec
UPDATE team_members
SET left_at = now()
WHERE team_id = $1 AND user_id = $2
`

type RemoveTeamMemberParams struct {
	TeamID pgtype.UUID `json:"team_id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) RemoveTeamMember(ctx context.Context, arg RemoveTeamMemberParams) error {
	_, err := q.db.Exec(ctx, removeTeamMember, arg.TeamID, arg.UserID)
	return err
}
